### ISSUE TITLE
error android in test branch

### ISSUE THREAD

**Issue by hyuni** [bduyng/com.bduyng.intropages#5]
Hi~~

i found two error.
one is not merge issue.
other is image path issue.

but. fixed.
# 

fixed : master merge after 

error message

[ERROR] TiExceptionHandler: (main) [18604,19730] ----- Titanium Javascript Runtime Error -----
[ERROR] TiExceptionHandler: (main) [0,19730] - In alloy/widgets/com.bduyng.intropages/controllers/widget.js:42,37
[ERROR] TiExceptionHandler: (main) [0,19730] - Message: Uncaught TypeError: Cannot read property 'opacity' of undefined
[ERROR] TiExceptionHandler: (main) [0,19730] - Source: front.opacity = e.source.opacity;
[ERROR] V8Exception: Exception occurred at alloy/widgets/com.bduyng.intropages/controllers/widget.js:42: Uncaught TypeError: Cannot read property 'opacity' of undefined
# 

fixed : can't find image files. --> assets/android/images/

error message

[ERROR] TiExceptionHandler: (main) [4,709] ----- Titanium Javascript Runtime Error -----
[ERROR] TiExceptionHandler: (main) [0,709] - In alloy/widgets/com.bduyng.intropages/controllers/widget.js:104,43
[ERROR] TiExceptionHandler: (main) [0,709] - Message: Uncaught TypeError: Cannot read property 'width' of null
[ERROR] TiExceptionHandler: (main) [0,709] - Source:         var originalImageWidth = imageBlob.width;
[DEBUG] dalvikvm: GC_FOR_ALLOC freed 115K, 4% free 6149K/6404K, paused 2ms, total 2ms
[WARN]  TiDrawableReference: (pool-3-thread-1) [7,716] Could not open stream to get bitmap
[ERROR] V8Exception: Exception occurred at alloy/widgets/com.bduyng.intropages/controllers/widget.js:104: Uncaught TypeError: Cannot read property 'width' of null

**Comment by bduyng** [comment]
@hyuni Thanks for your feedback. I updated the code and tested on my Android. can you please from your side and feel free to open this issue again if it still happen. Cheers!
