### ISSUE TITLE
opacity error on Android

### ISSUE THREAD

**Issue by safadig** [bduyng/com.bduyng.intropages#7]
Again, great widget but still having difficulty on Android running test app.
Opacity error on Android:
"Uncaught TypeError: Cannot read property 'opacity' of undefined
Is it possible to update test App to have Android as well? Excuse my limited knowledge
Thanks again

**Comment by bduyng** [comment]
@safadig. Thanks for your feedback. Don't have time to look into the issue until now. I updated the code and tested on my Android device. Can you please check the widget again on [test](https://github.com/bduyng/com.bduyng.intropages/tree/test) branch. Feel free to open this issue again if it still happens. Cheers!
